// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed Resources/Images/KrankyBearUSArmyCombatHelmetWoodland.png
var resourceKrankyBearUSArmyCombatHelmetWoodlandPngData []byte
var resourceKrankyBearUSArmyCombatHelmetWoodlandPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/KrankyBearUSArmyCombatHelmetWoodland.png",
	StaticContent: resourceKrankyBearUSArmyCombatHelmetWoodlandPngData,
}

//go:embed Resources/Images/tanium.png
var resourceTaniumPngData []byte
var resourceTaniumPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/tanium.png",
	StaticContent: resourceTaniumPngData,
}

//go:embed Resources/Images/KrankyBearHardHat.png
var resourceKrankyBearHardHatPngData []byte
var resourceKrankyBearHardHatPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/KrankyBearHardHat.png",
	StaticContent: resourceKrankyBearHardHatPngData,
}

//go:embed Resources/Sounds/wheeHoo.mp3
var resourceWheeHooMp3Data []byte
var resourceWheeHooMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/wheeHoo.mp3",
	StaticContent: resourceWheeHooMp3Data,
}

//go:embed Resources/Sounds/zip.mp3
var resourceZipMp3Data []byte
var resourceZipMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/zip.mp3",
	StaticContent: resourceZipMp3Data,
}

//go:embed Resources/Sounds/boing.mp3
var resourceBoingMp3Data []byte
var resourceBoingMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/boing.mp3",
	StaticContent: resourceBoingMp3Data,
}

//go:embed Resources/Sounds/explosion.mp3
var resourceExplosionMp3Data []byte
var resourceExplosionMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/explosion.mp3",
	StaticContent: resourceExplosionMp3Data,
}
