[Details]
ID = "com.github.amarillier.KrankyBearThreatInvaders"
Name = "KrankyBear ThreatInvaders"
Creator = "Allan Marillier"
Version = "0.1.0"
Build = 2
Icon = "KrankyBearUSArmyCombatHelmetWoodland.png"

[Migrations]
  fyneDo = true

[Development]
  HelperText = "This binary was built with debug symbols"

[Release]
  HelperText = "This binary was built without debug symbols"